### ISSUE TITLE
Autostyle button should not be enabled if autostyler can't provide a colors range 

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#513]
Original ticket: https://github.com/CartoDB/cartodb-management/issues/4815.

Let me show the problem with an example:

**STEPS TO REPRODUCE IT (BUILDER)**
- Create a map with a layer of points.
- Take a column where there are different values, it doesn't matter if it is string or number.
- In my case I'll take a number column called "count".
- Add a new histogram widget, using that "count" column.
- Go to the style tab, and add a custom style. It could be:

```css
#layer {
   marker-fill-opacity: 0.9;
   marker-line-color: #FFF;
   marker-line-width: 1;
   marker-line-opacity: 1;
   marker-placement: point;
   marker-type: ellipse;
   marker-width: 20;
   marker-allow-overlap: true;
}

#layer[count=100] {
   marker-file: url(ANYURL);
}
#layer[count<100] {
   marker-file: url(ANYURL);
}
```
- The important part is that there is a marker-file without any marker-fill.
- Refresh the page.
- 💥 .

This is due to we try to get the autostyle colors in order to pre-generate the ramps but there are not colors provided from the AutoStyler, so d3 interpolation fails. That's the first problem, but easy to solve with a `return` when `colorsRange` is undefined.

- If you fix that ^^^, refresh the page and check that the map is working again.
- Click now in the autostyle button.
- 💥 .

We should not display the autostyle button because there is no possibility to autostyle anything, the style is custom and there are icons/images, not "simple" colors. We should hide the button in this case.

cc @nobuti
