### ISSUE TITLE
Map options not working (scroll zoom and menu)

### ISSUE THREAD

**Issue by arredond** [CartoDB/deep-insights.js#548]
Steps to reproduce:

1. Make a map in Builder.
2. Activate scroll zoom and deactivate the menu bar
3. Export the viz.json. In map options, you'll see that

```js
"options": {
  "scrollwheel": true,
  "dashboard_menu": false
},
```
4. `cartodb.deepInsights.createDasbhoard` using the exported viz.json

The menu can be overriden in the app's CSS but this is sub-optimal

``` css
.CDB-Dashboard-menuInner {
  display:none !important;
}
.CDB-Dashboard-mapWrapper--withMenu {
  margin-left: 0;
}
```
